name: Deploy To Other Platform!

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Github Build and Publish]
    types: 
      - completed

jobs:
  deploy2vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy to Vercel
        run: |
          vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      - name: Deploy to Server
        if: false
        uses: actions/checkout@v3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          EXCLUDE: ".well-known"
          SOURCE: "./public/*"
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: "root"
          TARGET: "/home/application"
    