name: Deploy To Other Platform!

on:
  workflow_run:
    workflows: [Github Build and Publish]
    types: 
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            ref: gh-pages
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy to Vercel
        run: |
            prodRun=""
            if [[ ${GITHUB_REF} == "refs/heads/gh-pages" ]]; then
              prodRun="--prod"
            fi
            vercel --token ${VERCEL_TOKEN} ${prodRun}
        env:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        # - name: Deploy to Server # 部署到自己的服务器上！
        #   uses: easingthemes/ssh-deploy@v2
        #   env:
        #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        #     ARGS: "-rltgoDzvO --delete"
        #     EXCLUDE: ".well-known"
        #     SOURCE: "./public/*"
        #     REMOTE_HOST: ${{ secrets.SERVER_IP }}
        #     REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        #     REMOTE_USER: "你的用户名"
        #     TARGET: "你的服务器绝对路径"
  on-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
          - run: echo 'The triggering workflow failed'
    