name: Github Build and Publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16,4 * * *' # every day at midnight and noon（Use UTC time,China Standard Time is UTC:+8:00）
  push:
    branches:
      - develop # develop branch
      - main # default branch
  pull_request:
    branches:
      - develop # develop branch
      - main # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install pandoc for mathjax
        run: |
          cd /tmp
          if [ type pandoc > /dev/null 2>&1 ]; then
            echo 'Already installed pandoc!'
          else
            if [ -f pandoc-3.1.6.1-1-amd64.deb ]; then
              echo 'Already downloaded pandoc!'
            else
              wget -cq https://github.com/jgm/pandoc/releases/download/3.1.6.1/pandoc-3.1.6.1-1-amd64.deb -O pandoc-3.1.6.1-1-amd64.deb
              echo 'Pandoc download successful!'
            fi
            sudo dpkg -i pandoc-3.1.6.1-1-amd64.deb
            pandoc --version
            echo 'Pandoc install successful!'
          fi
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Install Dependencies
        run: |
          pnpm install
          pnpm install --global gulp-cli
      - name: Build Dist and Index
        run: |
          pnpm run clean
          pnpm run spider
          pnpm run build
          pnpm run algolia
      - name: Compress static resource
        run: |
          gulp
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
   