
name: Hexo SEO Auto Push

on:
  schedule:
    - cron: 0 4 * * *
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || github.event_name == 'schedule'
    steps:

      - name: 1. Checkout the code
        uses: actions/checkout@v3

      - name: 2. Install Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 3. Install the Plugin of 
        run: |
          npm install hexo-seo-integrated-submit -g

      - name: 4. Google submit
        if: true
        run: hexo-sis google -e "${{secrets.google_client_email}}" -k "${{secrets.google_private_key}}"

      - name: 5. Bing submit
        if: true
        run: hexo-sis bing -k "${{secrets.bing_apikey}}"

      - name: 6. Baidu submit
        if: true
        run: hexo-sis baidu -k "${{secrets.baidu_token}}"
